# Directories to backup (space-separated)
SOURCE_DIRS="/home/ubuntu/test_backup_folder"

# Where backups will be stored
BACKUP_DIR="/home/ubuntu/devops-shell-projects/backup-manager/backups"

# Retention period (in days)
RETENTION_DAYS=7

# Log file location
LOG_FILE="/home/ubuntu/devops-shell-projects/backup-manager/logs/backup.log"
